
DROP TABLE IMAGEBOARD;

CREATE TABLE IMAGEBOARD(
	INO NUMBER PRIMARY KEY,
	IWRITER VARCHAR2(50) ,
	IFILENAME VARCHAR2(256),
	ITITLE VARCHAR2(1000),
	ICONTENT VARCHAR2(4000),
	IREGDATE DATE	
);


DROP SEQUENCE IMAGEBOARD_SEQ;
CREATE SEQUENCE IMAGEBOARD_SEQ
START WITH 1
INCREMENT BY 1
MAXVALUE 9999999
NOCYCLE
NOCACHE;
